language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

sudo: false

before_script:
  - (composer self-update; true)
  - composer install


script:
  - ./vendor/phpunit/phpunit/phpunit --coverage-clover clover.xml



